# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_engine_pb2 as ai__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIEngineStub(object):
    """Servicio principal del Motor de IA
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkerTask = channel.unary_unary(
                '/ai_engine.AIEngine/ExecuteWorkerTask',
                request_serializer=ai__engine__pb2.WorkerTaskRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.WorkerTaskResponse.FromString,
                _registered_method=True)
        self.StreamWorkerProgress = channel.unary_stream(
                '/ai_engine.AIEngine/StreamWorkerProgress',
                request_serializer=ai__engine__pb2.WorkerTaskRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.WorkerProgressUpdate.FromString,
                _registered_method=True)


class AIEngineServicer(object):
    """Servicio principal del Motor de IA
    """

    def ExecuteWorkerTask(self, request, context):
        """Ejecuta una tarea técnica pesada (ej: scraping, análisis de datos)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWorkerProgress(self, request, context):
        """Permite ver el razonamiento y progreso del worker en tiempo real
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWorkerTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkerTask,
                    request_deserializer=ai__engine__pb2.WorkerTaskRequest.FromString,
                    response_serializer=ai__engine__pb2.WorkerTaskResponse.SerializeToString,
            ),
            'StreamWorkerProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWorkerProgress,
                    request_deserializer=ai__engine__pb2.WorkerTaskRequest.FromString,
                    response_serializer=ai__engine__pb2.WorkerProgressUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_engine.AIEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_engine.AIEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIEngine(object):
    """Servicio principal del Motor de IA
    """

    @staticmethod
    def ExecuteWorkerTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/ExecuteWorkerTask',
            ai__engine__pb2.WorkerTaskRequest.SerializeToString,
            ai__engine__pb2.WorkerTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWorkerProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_engine.AIEngine/StreamWorkerProgress',
            ai__engine__pb2.WorkerTaskRequest.SerializeToString,
            ai__engine__pb2.WorkerProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
