[project]
name = "ai-engine"
version = "0.1.0"
description = "Motor de razonamiento pesado y workers especializados en Python."
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.27.0",
    "grpcio>=1.62.0",
    "grpcio-tools>=1.62.0",
    "pydantic>=2.6.0",
    "python-dotenv>=1.0.1",
    "protobuf>=4.25.0",
    "pytest>=8.0.0",
    "ruff>=0.3.0",
    "opentelemetry-api>=1.25.0",
    "opentelemetry-sdk>=1.25.0",
    "opentelemetry-exporter-otlp>=1.25.0",
    "opentelemetry-instrumentation-grpc>=0.46b0"
]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["app/grpc_generated"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
